### ISSUE TITLE
Import torch_scatter, Segmentation fault occurs

### ISSUE THREAD

**Issue by Grandzxw** [fcchit/CFPR#2]
My enviroment is ubuntu 16.04, python 3.7, torch 1.2.1, cuda 10.2

**Comment by Grandzxw** [comment]
When load the pretrained_backbone_model, some errors happen:
    **raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for backbone:
	size mismatch for dconv_down1.conv.3.weight: copying a param with shape torch.Size([11, 11, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 11, 11, 16]).
	size mismatch for dconv_down1_1.conv.3.weight: copying a param with shape torch.Size([11, 11, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 11, 11, 16]).
	size mismatch for dconv_down2.conv.3.weight: copying a param with shape torch.Size([7, 7, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 7, 7, 32]).
	size mismatch for dconv_down2_1.conv.3.weight: copying a param with shape torch.Size([7, 7, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 7, 7, 32]).**

Can you upload the correct pretrained_backbone_model?

**Comment by guan2000910** [comment]
I have the same confusion as you, may I ask if you have solved the problem?

**Comment by fcchit** [comment]
This is caused by spconv version mismatch, please install spconv-cu102=2.1.25.
`pip install spconv-cu102==2.1.25`
In addition, there is no need to `import torch_scatter`, it is not used.

**Comment by whu-lyh** [comment]
same error

**Comment by fcchit** [comment]
You can try to use the docker image `fuchencan/onv`. @whu-lyh @Grandzxw @guan2000910

**Comment by whu-lyh** [comment]
Thank you ChengCan, I solved by permute the tensor, the teaser code is list, my sparse conv library version is  `spconv-cu116`
```
for k, v in model_dict.items():
      # 1.x checkpoint weight migrate to 2.x
      if k == 'dconv_down1.conv.3.weight' or k == 'dconv_down1_1.conv.3.weight' \
          or k== 'dconv_down2.conv.3.weight' or k == 'dconv_down2_1.conv.3.weight':
          model_dict[k] = v.permute(3, 0, 1, 2).contiguous()
```

**Comment by zw-92** [comment]
> You can try to use the docker image `fuchencan/onv`. @whu-lyh @Grandzxw @guan2000910您可以尝试使用docker镜像fuchencan/onv。 @whu-lyh @Grandzxw @guan2000910

Hello, I have downloaded the docker image you mentioned, but there is no environment required by the project.

**Comment by fcchit** [comment]
> > You can try to use the docker image `fuchencan/onv`. @whu-lyh @Grandzxw @guan2000910您可以尝试使用docker镜像fuchencan/onv。 @whu-lyh @Grandzxw @guan2000910
> 
> Hello, I have downloaded the docker image you mentioned, but there is no environment required by the project.

Hello @zw-92,

I checked the Docker image, and you may need to run `conda activate onv` to activate the conda environment within the Docker container.

Additionally, I will check and update this repository in December, as the paper and code have changed in the ICRA version.
