### ISSUE TITLE
Do you manually cull some data from KITTI07 sequence?

### ISSUE THREAD

**Issue by whu-lyh** [fcchit/CFPR#3]
Hi Chencan, thanks for your amazing work and for releasing the code. Recently, I try to train your model based on your codes. But I meet some errors. The following error is tricky:
```
Traceback (most recent call last):
  File "/workspace/OverlapNetVLAD/train/train_netvlad.py", line 121, in <module>
    train(config)
  File "/workspace/OverlapNetVLAD/train/train_netvlad.py", line 104, in train
    recall = evaluate.evaluate_vlad(vlad)
  File "/workspace/OverlapNetVLAD/evaluate/evaluate.py", line 90, in evaluate_vlad
    vlad_dis[mask] = np.inf
  IndexError: boolean index did not match indexed array along dimension 0; dimension is 1099 but corresponding boolean dimension is 1101
```
Where should I be carefully noted?
Besides, I found that the training process is slow, the GPU Usage is quite low. I set the `num_works` which is maximum at my machine, and the batch_size is 64. But, apparently, it is not the correct solution.

**Comment by fcchit** [comment]
Thanks for checking out and supporting this project! I didn't run into the error you mentioned during my tests. You can chech if the code is all up-to-date.

Training does take a while. One trick I thought of is using torch.Tensor instead of numpy.array. This may help train faster.

**Comment by whu-lyh** [comment]
my data is incomplete... thanks anyway
